export enum OrderType {
    RAILWAY_CONSTRUCTION = 1,
    TRADING = 2,
    MOVEMENT_OF_DETACHMENTS = 3,
    DEPLOYMENT_OF_INDIAN_TROOPS = 4,
    ATTACK_OF_INDIAN_TROOPS = 5,
    DESTRUCTION_OF_STATIONS = 6,
    DESTRUCTION_OF_INDIAN_SETTLEMENTS = 7,
    EXHIBITING_INDIAN_REVENGE = 8,
    RESTORATION_OF_INDIAN_SETTLEMENTS = 9,
    DEPLOYMENT_OF_NEW_DETACHMENTS_OF_RAILWAY_SECURITY = 10,
    CHANGING_IMPACT_OF_PR = 11,
    CHANGING_IMPACT_FROM_ROADS = 12,
    CHANGING_POLITICAL_AFFILIATION_OF_CITIES = 13,
    DISTRIBUTION_OF_INFLUENCE_OF_POLITICIANS_IN_CITIES = 14,
    RESTORATION_OF_LOST_ARMIES = 15,
    PURCHASE_OF_NEW_ORDERS = 16
}
