export enum PriorityPolicyProcessing {
    CHANGING_IMPACT_OF_PR = 1,
    CHANGING_IMPACT_FROM_ROADS = 2,
    CHANGING_POLITICAL_AFFILIATION_OF_CITIES = 3,
    DISTRIBUTION_OF_INFLUENCE_OF_POLITICIANS_IN_CITIES = 4,
    RESTORATION_OF_LOST_ARMIES = 5
}
