export enum PriorityWarProcessing {
    MOVEMENT_OF_DETACHMENTS = 1,
    DEPLOYMENT_OF_INDIAN_TROOPS = 2,
    ATTACK_OF_INDIAN_TROOPS = 3,
    DESTRUCTION_OF_STATIONS = 4,
    DESTRUCTION_OF_INDIAN_SETTLEMENTS = 5,
    EXHIBITING_INDIAN_REVENGE = 6,
    RESTORATION_OF_INDIAN_SETTLEMENTS = 7,
    DEPLOYMENT_OF_NEW_DETACHMENTS_OF_RAILWAY_SECURITY = 8
}
