export enum TeamId {
  GAME_TECHNICIAN = 0, 
  SOUTH_EASTERN_RAILWAY = 1,
  PACIFIC_RAILWAY = 2,
  SOUTH_WESTERN_RAILWAY = 3,
  NORTHERN_RAILWAY = 4,
  NEW_YORK_RAILWAY = 5,
  TEXAS_RAILWAY = 6,
  FEDERATION = 7,
  CONFEDERATION = 8,
  REPUBLIC = 9,
  PRESCOTT = 10,
  WASHINGTON = 11,
  BISMARCK = 12,
  LITTLE_ROCK = 13
}
